### PR TITLE
126-Chore: Export IERC20 artifact

### LINKED ISSUE #126: Chore: Export interface ABI in addition to contract ABI
## User Story
**As a** dApp dev, **I want to** have the interface artifact for ERC20 tokens readily available in the repository.

## Status Quo
- we export ERC20 contract ABI in `sharedAbis.json`

## Acceptance Criteria
- we export ERC20 and IERC20 ABI in `sharedAbis.json`

### PR DESCRIPTION
**Pull request by fabianschu**
### What's new?
- the IERC20 ABI is included in `sharedAbis.json`

closes #126

### CODE REVIEW

**Comment by fabianschu** [comment]
@dkent600 Is this the way you envisioned this?

**Review by Zitzak — DISMISSED** [review]
So if I followed the conversation yesterday in telegram correctly then what happened here is, instead of using the ERC20 token ABI we're going to use the interface ABI IERC20. In this way we save storage and we have one interface for multiple ERC20 contracts, instead of artifacts for each. Is that correct?

**Comment by dkent600** [comment]
> So if I followed the conversation yesterday in telegram correctly then what happened here is, instead of using the ERC20 token ABI we're going to use the interface ABI IERC20. In this way we save storage and we have one interface for multiple ERC20 contracts, instead of artifacts for each. Is that correct?

No longer entirely correct.  The need has evolved a bit:  We need both IERC20 and ERC20 artifacts.

**Comment by fabianschu** [comment]
@dkent600 re: `Can you please summarize for me what will be required for the consumer (dapp) to obtain ERC20 and IERC20 artifacts, and for deployed contracts, to obtain the artifact plus address?`

1. obtain ERC and IERC20 artifacts: Import `sharedAbis.json`. This is a JSON object that contains two keys currently: `ERC20` and `IERC20`, which in turn have the respective ABIs as values.
2. artifacts and addresses of deployed contracts: depending on which network you need import either `mainnet.json` or `rinkeby.json`. Both files are JSON objects which contain the various deployed contract names as keys. Each contract contains 2-3 keys: `address`, `abi` and optionally `interfaceAbi`. As per your wish to keep these files small, contracts that share an abi (e.g. ERC20 tokens) do not contain the abi under the key `abi` but a string of the name of the abi, that can be used to obtain the actual abi from `sharedAbis.json`.

**Comment by dkent600** [comment]
> If this is not necessary, we could remove this optional third field and just make sure that the IERC20 abi is included in `sharedAbis.json`. What do you think?

It does not appear to be necessary for satisfying my needs such as I described above.  I would remove it.

**Review by Zitzak — APPROVED** [review]

**Review by codebuster22 — APPROVED** [review]
lgtm

**Pull request merged**
