### PR TITLE
119 hundred percent test coverage for reputation

### LINKED ISSUE #119: Chore: 100% branch coverage for Reputation

### PR DESCRIPTION
**Pull request by fabianschu**
closes #119

### CODE REVIEW

**Review by BritikovKI — APPROVED** [review]
Lgtmt

**Comment by BritikovKI** [comment]
Coverage isn't a hundred still though ;-)

**Comment by fabianschu** [comment]
for **Reputation!** contract :-P

**Review by codebuster22 — APPROVED** [review]
lgtm

**Pull request merged**
